name: Build and Test Common C++

pr:
- master
- develop

trigger: none

stages:

- stage: Windows
  dependsOn: []
  pool:
    name: Hosted VS2017
    demands:
    - msbuild
    - vstest

  jobs:
  - job: Build_And_Test_VisualStudio
    strategy:
      maxParallel: 1
      matrix:
        debug x86:
          BuildConfiguration: Debug
          BuildPlatform: x86
          BuildDirectory: Debug
        release x86:
          BuildConfiguration: Release 
          BuildPlatform: x86
          BuildDirectory: Release
        debug x64:
          BuildConfiguration: Debug
          BuildPlatform: x64
          BuildDirectory: x64/Debug
        release x64:
          BuildConfiguration: Release  
          BuildPlatform: x64  
          BuildDirectory: x64/Release
    steps:
    - template: ci/steps-windows-test-vs.yml
      parameters:
        buildPlatform: '$(BuildPlatform)'
        buildConfiguration: '$(BuildConfiguration)'
        buildDirectory: '$(BuildDirectory)'

  - job: Build_And_Test_CMake  
    strategy:
      maxParallel: 1
      matrix:
        debug x86:
          BuildConfiguration: Debug
          BuildPlatform: Win32
        release x86:
          BuildConfiguration: Release 
          BuildPlatform: Win32
        debug x64:
          BuildConfiguration: Debug
          BuildPlatform: x64
        release x64:
          BuildConfiguration: Release  
          BuildPlatform: x64   
    steps:
    - template: ci/steps-windows-test-cmake.yml
      parameters:
        buildPlatform: '$(BuildPlatform)'
        buildConfiguration: '$(BuildConfiguration)'

- stage: Mac
  dependsOn: []
  jobs:
  - template: ci/job-mac-test.yml
        
- stage: Linux
  dependsOn: []
  jobs:
  - template: ci/job-linux-test.yml
