jobs:
- job: Build_And_Test_Ubuntu
  timeoutInMinutes: 120
  pool:
    name: Hosted Ubuntu 1604
  steps:
  - checkout: self
    submodules: recursive
    lfs: true

  - task: Bash@3
    displayName: 'Create Build Directory'
    inputs:
      targetType: 'inline'
      script: 'mkdir build'

  - task: CMake@1
    displayName: 'CMake Configure'
    inputs:
      workingDirectory: build
      cmakeArgs: '..'

  - task: CMake@1
    displayName: 'CMake Build'
    inputs:
      workingDirectory: build
      cmakeArgs: '--build .'

  - bash: 'ctest -T test --no-compress-output'
    workingDirectory: build
    failOnStderr: true
    displayName: 'Run Tests'

  - task: PublishTestResults@2
    condition: true
    inputs:
      testResultsFormat: 'CTest'
      testRunTitle: 'Linux CTest'
      testResultsFiles: '**/Test.xml'